### PR TITLE
573 | Add feature for deleting tickets permanently

### PR DESCRIPTION
**Pull request by PalaniappanC**
https://github.com/Speedygeek/ZendeskApi_v2/issues/573

Adding a feature for deleting tickets permanently

### CODE REVIEW

**Review by mozts2005 — CHANGES_REQUESTED** [review]
Please add the async methods as well

**Comment by PalaniappanC** [comment]
> Please add the async methods as well

Hi @mozts2005 I have added the async methods also

**Comment by PalaniappanC** [comment]
> Please add the async methods as well


Hi @mozts2005 I have added the async methods also

**Comment by PalaniappanC** [comment]
Can you add the hacktoberfest-accepted label if it takes time to merge the PR.

**Review by mozts2005 — APPROVED** [review]
looks good thanks for adding the async.

**Pull request merged**
