### PR TITLE
adding support for followUpIds in tickets

### PR DESCRIPTION
**Pull request by yuvalon**
adding the property of "FollowUpIds", in Ticket model.

### CODE REVIEW

**Comment by yuvalon** [comment]
The specific automated test that is failing, is failing also before my changes. It does not have to do with the changes I had proposed.

**Comment by mozts2005** [comment]
Please, add a test case

**Comment by yuvalon** [comment]
I added the relevant test. thank you.

**Comment by yuvalon** [comment]
looks like testing results are alright!

**Pull request merged**
