### PR TITLE
Update From.cs

### PR DESCRIPTION
**Pull request by washamdev**
When a Ticket was created as a follow-up to a closed ticket, the `via.source.from.ticket_id` property comes back from the API. Is this all that is needed to fill out the `TicketId` property here?

### CODE REVIEW

**Comment by washamdev** [comment]
This Pull Request is related to #427.

**Comment by mozts2005** [comment]
Please fix your failing test case.

Note: you can update this pull request by just adding more commits to you current branch. (you will need to run a sync to get the other updates.)

**Comment by washamdev** [comment]
Hopefully I'm not missing something here due to being new to Git pull requests, but when I viewed the details of the failed test case, none of the items were related to my change. I then visited my repository from ZendeskApi_2, but there was no Sync action to take. Is there truly something for me to fix? Thanks!

**Comment by mozts2005** [comment]
to sync you will need to run "git sync" on your local computer. if that dose not update your local code then more info can be found here: https://help.github.com/en/articles/syncing-a-fork

as for the failing test I have fix the issue that was making most of them fail. the only one left is only in your pull request so it has to be based on your code change. 

see here: https://dev.azure.com/speedygeek/Zendesk/_build/results?buildId=233&view=ms.vss-test-web.build-test-results-tab&runId=1000216&resultId=100199&paneView=debug
the name of the failing test is SerializeAllFieldsTest

**Comment by mozts2005** [comment]
see pr #436 for fix

**Pull request closed without merging**
